#!/bin/sh
# Данный комментарий сообщает системе, что следующий за ним аргумент - программа, применяемая для выполнения данного файла

myvar="Hi there"
echo $myvar
echo "$myvar"
echo '$myvar'
echo \$myvar

echo Enter some text
read myvar

echo '$myvar' now equals $myvar
exit 0

# Для присвоения сценарию статуса других команд Linux используется команда $ chmod +x 'имя сценария'
# Для поиска выполняяемых команд необходимо задать текущий каталог в PATH. Команда PATH=$PATH:. позволяет сделать это
