#!/bin/bash

# Этот файл должен находиться по пути /usr/local/bin
file="$1"
extension="$2"

echo "Открытие файла $file с расширением: $extension"

case "$extension" in
    txt) xdg-open "$file" ;;
    pdf) xdg-open "$file" ;;
    png|jpg|jpeg) xdg-open "$file" ;;
    *) 
        echo "Неизвестное расширение: $extension"
        exit 1
        ;;
esac
